FROM php:8.2-alpine

RUN apk --no-cache add $PHPIZE_DEPS git unzip linux-headers
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . ./

RUN composer install --no-dev

CMD ["php", "-S", "0.0.0.0:8080", "-t", "/app", "/app/index.php"]